# Upptime configuration - Triggering workflow restart
# Change these first
owner: fieldingtron # Your GitHub organization or username, where this repository lives
repo: upptest # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: "80"
    check: "tcp-ping"
    ipv6: true
  - name: abnzb
    url: https://abnzb.com/login
    __slug: /abnzb-review/
    type: globalping
    method: GET
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    maxResponseTime: "10000"
    expectedStatusCodes:
      - "200"
      - "301"
      - "302"
      - "403"
  - name: althub
    url: https://althub.co.za
    __slug: /althub-review/
  - name: binnewz
    url: https://www.forum.binnews.ninja/
    __slug: /binnewz-review/
    type: globalping
  - name: binsearch
    url: https://binsearch.info/
    __slug: /binsearch-review/
  - name: binzb
    url: http://binzb.com/
    __slug: /binzb-review/
    type: globalping
    check: "tcp-ping"
  - name: birds-of-binaries
    url: https://birds-of-binaries.com/forum/index.php?dashboard/
    __slug: /birds-of-binaries-review/
  - name: bluraynzb
    url: https://www.bluraynzb.org/
    __slug: /bluraynzb-review/
  - name: brothers-of-usenet
    url: https://www.brothers-of-usenet.net/
    __slug: /brothers-of-usenet-review/
    type: globalping
    check: "tcp-ping"
  - name: dognzb
    url: https://dognzb.cr/login
    __slug: /dognzb-review/
    type: globalping
  - name: drunken-slug
    url: https://drunkenslug.com/
    __slug: /drunken-slug-review/
    type: globalping
  - name: easy-leech
    url: https://easy-leech.to/
    __slug: /easy-leech-review/
  - name: elitenzb
    url: https://www.elitenzb.info/
    __slug: /elitenzb-review/
  - name: fileleechers
    url: https://fileleechers.info/board/index.php?login/&url=https%3A%2F%2Ffileleechers.info%2Fboard%2F
    __slug: /fileleechers-review/
  - name: FileSharingTalk
    url: https://filesharingtalk.com/nzbs/
    __slug: "N/A"
    type: globalping
    check: "tcp-ping"
  - name: findnzb
    url: http://findnzb.net/
    __slug: /findnzb-review/
    type: globalping
    check: "tcp-ping"
  - name: gingadaddy
    url: https://www.gingadaddy.com
    __slug: /gingadaddy-review/
  - name: headphones-vip
    url: https://headphones.codeshy.com/vip/
    __slug: /headphones-vip-review/
  - name: house-of-usenet
    url: https://house-of-usenet.com/login
    __slug: /house-of-usenet-review/
  - name: miatrix
    url: https://www.miatrix.com
    __slug: /miatrix-review/
  - name: newz-complex
    url: https://newz-complex.org/
    __slug: "N/A"
  - name: newzfinders
    url: http://en.newzfinders.com/
    __slug: "N/A"
  - name: newznzb
    url: https://newznzb.info/
    __slug: /newznzb-review/
    type: globalping
  - name: ninjacentral
    url: http://ninjacentral.co.za/
    __slug: /ninjacentral-review/
    type: globalping
  - name: nzbking
    url: http://www.nzbking.com/
    __slug: /nzbking-review/
  - name: nzbnation
    url: http://nzbnation.com/
    __slug: /nzbnation-review/
  - name: NZB Su
    url: https://www.nzb.su/
    __slug: "N/A"
    type: globalping
  - name: nzbwolf
    url: https://nzbwolf.com/
    __slug: /nzbwolf-review/
  - name: nzbcat
    url: https://nzb.cat
    __slug: /nzbcat-review/
    type: globalping
    check: "tcp-ping"
    port: "443"
  - name: nzbcave
    url: https://www.nzbcave.co.uk/v3/index.php
    __slug: /nzbcave-review/
  - name: nzbfinder
    url: https://nzbfinder.ws/
    __slug: /nzbfinder-review/
    type: globalping
  - name: nzbforyou
    url: https://www.nzbforyou.com/
    __slug: /nzbforyou-review/
  - name: NZBFriends
    url: http://nzbfriends.com/
    __slug: "N/A"
    type: globalping
  - name: nzbgeek
    url: https://nzbgeek.info
    __slug: /nz-bgeek-review/
    type: globalping
  - name: NZBGrabit
    url: https://www.nzbgrabit.org/forum.php
    __slug: "N/A"
    type: globalping
    method: GET
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    maxResponseTime: "10000"
    expectedStatusCodes:
      - "200"
      - "301"
      - "302"
      - "403"
  - name: nzbhunter
    url: https://nzbhunter.com/
    __slug: /nzbhunter-review/
  - name: nzb-id
    url: https://nzbid.net/
    __slug: /nzb-id-review/
    type: globalping
    check: "tcp-ping"
  - name: nzbindex
    url: https://www.nzbindex.com/search
    __slug: /nzbindex-review/
  - name: NZBIndex.nl
    url: https://nzbindex.nl/
    __slug: "N/A"
  - name: nzbnewzfrance
    url: https://www.nzbnewzfrance.ninja/
    __slug: /nzbnewzfrance-review/
    type: globalping
  - name: nzbnoob
    url: https://nzbnoob.com
    __slug: /nzbnoob-review/
    type: globalping
  - name: nzbplanet
    url: https://nzbplanet.net/
    __slug: "N/A"
    type: globalping
  - name: nzbs2go
    url: https://nzbs2go.com/login
    __slug: /nzbs2go-review/
    type: globalping
  - name: nzbscc
    url: https://nzbs.cc/
    __slug: /nzbscc-review/
    type: globalping
  - name: nzbscout
    url: https://nzbscout.com/
    __slug: /nzbscout-review/
    type: globalping
  - name: nzbserver
    url: http://www.nzbserver.com
    __slug: /nzbserver-review/
    type: globalping
  - name: nzbstars
    url: https://www.nzbstars.com/
    __slug: /nzbstars-review/
    type: globalping
  - name: nzbxs
    url: https://www.nzbxs.com/
    __slug: /nzbxs-review/
  - name: omgwtfnzbs
    url: https://omgwtfnzbs.me/login
    __slug: /omgwtfnzbs-review/
    type: globalping
  - name: pourcesoir
    url: https://pourcesoir.in/
    __slug: /pourcesoir-review/
  - name: scenenzbs
    url: https://scenenzbs.com/
    __slug: /scenenzbs-review/
  - name: Sky of Usenet
    url: https://sky-of-use.net/index.php?login/&url=https%3A%2F%2Fsky-of-use.net%2F
    __slug: "N/A"
    type: globalping
  - name: tabula-rasa
    url: https://www.tabula-rasa.pw
    __slug: /tabula-rasa-review/
  - name: The Hive
    url: http://www.the-hive.be/forum/
    __slug: "N/A"
  - name: Usenet Hub
    url: http://usenethub.com/
    __slug: "N/A"
  - name: usenetcrawler
    url: http://usenet-crawler.com
    __slug: "N/A"
  - name: usenethd
    url: https://www.usenethd.li/login/
    __slug: /usenethd-review/
  - name: wtfnzb
    url: http://wtfnzb.pw/
    __slug: /wtfnzb-review/
    type: globalping
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptest
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  uptime: "*/15 * * * *"

